/**
 * React Query Keys
 * Bruno 폴더 구조를 기반으로 자동 생성됨
 */

export const QueryKeys = {
  Auth: {
    folder: 'Auth.folder' as const,
    signOut: 'Auth.signOut' as const,
    appleAuth: 'Auth.appleAuth' as const,
    refreshToken: 'Auth.refreshToken' as const,
    emailLogin: 'Auth.emailLogin' as const,
    emailVerification: 'Auth.emailVerification' as const,
    kakaoAuth: 'Auth.kakaoAuth' as const,
    account: 'Auth.account' as const,
    signUp: 'Auth.signUp' as const,
  },
  news: {
    folder: 'news.folder' as const,
    newsList: 'news.newsList' as const,
    news: 'news.news' as const,
    updateNews: 'news.updateNews' as const,
    likeNews: 'news.likeNews' as const,
    createNews: 'news.createNews' as const,
  },
  reports: {
    folder: 'reports.folder' as const,
    report: 'reports.report' as const,
  },
  chat: {
    folder: 'chat.folder' as const,
    chatMessages: 'chat.chatMessages' as const,
    chatRooms: 'chat.chatRooms' as const,
    readChatRoom: 'chat.readChatRoom' as const,
    chatPartner: 'chat.chatPartner' as const,
  },
  universities: {
    folder: 'universities.folder' as const,
    recommendedUniversities: 'universities.recommendedUniversities' as const,
    wishList: 'universities.wishList' as const,
    wish: 'universities.wish' as const,
    addWish: 'universities.addWish' as const,
    isWish: 'universities.isWish' as const,
    universityDetail: 'universities.universityDetail' as const,
    searchText: 'universities.searchText' as const,
    byRegionCountry: 'universities.byRegionCountry' as const,
  },
  MyPage: {
    folder: 'MyPage.folder' as const,
    interestedRegionCountry: 'MyPage.interestedRegionCountry' as const,
    profile: 'MyPage.profile' as const,
    password: 'MyPage.password' as const,
  },
  applications: {
    folder: 'applications.folder' as const,
    competitors: 'applications.competitors' as const,
    submitApplication: 'applications.submitApplication' as const,
    applicants: 'applications.applicants' as const,
  },
  community: {
    folder: 'community.folder' as const,
    boardList: 'community.boardList' as const,
    board: 'community.board' as const,
    comment: 'community.comment' as const,
    updateComment: 'community.updateComment' as const,
    createComment: 'community.createComment' as const,
    post: 'community.post' as const,
    updatePost: 'community.updatePost' as const,
    createPost: 'community.createPost' as const,
    postDetail: 'community.postDetail' as const,
    likePost: 'community.likePost' as const,
  },
  Scores: {
    folder: 'Scores.folder' as const,
    createLanguageTest: 'Scores.createLanguageTest' as const,
    languageTestList: 'Scores.languageTestList' as const,
    createGpa: 'Scores.createGpa' as const,
    gpaList: 'Scores.gpaList' as const,
  },
  Admin: {
    folder: 'Admin.folder' as const,
    멘토 승격 요청 거절: 'Admin.멘토 승격 요청 거절' as const,
    멘토 승격 요청 내역 조회: 'Admin.멘토 승격 요청 내역 조회' as const,
    멘토 요청 승격 처리: 'Admin.멘토 요청 승격 처리' as const,
    멘토 지원서 대학 매핑: 'Admin.멘토 지원서 대학 매핑' as const,
    멘토 지원서 상태별 개수 조회: 'Admin.멘토 지원서 상태별 개수 조회' as const,
    멘토 지원서 이력 조회: 'Admin.멘토 지원서 이력 조회' as const,
    verifyLanguageTest: 'Admin.verifyLanguageTest' as const,
    languageTestList: 'Admin.languageTestList' as const,
    verifyGpa: 'Admin.verifyGpa' as const,
    gpaList: 'Admin.gpaList' as const,
  },
  users: {
    folder: 'users.folder' as const,
    nicknameExists: 'users.nicknameExists' as const,
    blockUser: 'users.blockUser' as const,
    unblockUser: 'users.unblockUser' as const,
    blockedUsers: 'users.blockedUsers' as const,
  },
  mentor: {
    folder: 'mentor.folder' as const,
    matchedMentors: 'mentor.matchedMentors' as const,
    applyMentoring: 'mentor.applyMentoring' as const,
    confirmMentoring: 'mentor.confirmMentoring' as const,
    appliedMentorings: 'mentor.appliedMentorings' as const,
    mentorList: 'mentor.mentorList' as const,
    mentorDetail: 'mentor.mentorDetail' as const,
    myMentorPage: 'mentor.myMentorPage' as const,
    updateMyMentorPage: 'mentor.updateMyMentorPage' as const,
    mentoringStatus: 'mentor.mentoringStatus' as const,
    receivedMentorings: 'mentor.receivedMentorings' as const,
    unconfirmedMentoringCount: 'mentor.unconfirmedMentoringCount' as const,
    멘토 승격 요청: 'mentor.멘토 승격 요청' as const,
  },
  'kakao-api': {
    folder: 'kakao-api.folder' as const,
    kakaoUserIds: 'kakao-api.kakaoUserIds' as const,
    kakaoUnlink: 'kakao-api.kakaoUnlink' as const,
    kakaoInfo: 'kakao-api.kakaoInfo' as const,
  },
  environments: {
    dev: 'environments.dev' as const,
    local: 'environments.local' as const,
    prod: 'environments.prod' as const,
  },
  'image-upload': {
    folder: 'image-upload.folder' as const,
    slackNotification: 'image-upload.slackNotification' as const,
    uploadLanguageTestReport: 'image-upload.uploadLanguageTestReport' as const,
    uploadProfileImage: 'image-upload.uploadProfileImage' as const,
    uploadProfileImageBeforeSignup: 'image-upload.uploadProfileImageBeforeSignup' as const,
    uploadGpaReport: 'image-upload.uploadGpaReport' as const,
  },
} as const;

export type QueryKey = typeof QueryKeys[keyof typeof QueryKeys];