import type { AppliedMentoringsResponse, ApplyMentoringRequest, ApplyMentoringResponse, ConfirmMentoringRequest, ConfirmMentoringResponse, MatchedMentorsResponse, MentorDetailResponse, MentorListResponse, MentoringStatusRequest, MentoringStatusResponse, MyMentorPageResponse, ReceivedMentoringsResponse, UnconfirmedMentoringCountResponse, UpdateMyMentorPageRequest, UpdateMyMentorPageResponse } from './api';

export const mentorApiDefinitions = {
  getMatchedMentors: {
    method: 'GET' as const,
    path: '{{URL}}/mentee/mentorings/matched-mentors?size={{default-size}}&page={{default-page}}' as const,
    pathParams: {} as { defaultSize: string | number; defaultPage: string | number },
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as MatchedMentorsResponse,
  },
  postApplyMentoring: {
    method: 'POST' as const,
    path: '{{URL}}/mentee/mentorings' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, never>,
    body: {} as ApplyMentoringRequest,
    response: {} as ApplyMentoringResponse,
  },
  patchConfirmMentoring: {
    method: 'PATCH' as const,
    path: '{{URL}}/mentee/mentorings/check' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, never>,
    body: {} as ConfirmMentoringRequest,
    response: {} as ConfirmMentoringResponse,
  },
  getAppliedMentorings: {
    method: 'GET' as const,
    path: '{{URL}}/mentee/mentorings?verify-status={{verify-status}}&size={{default-size}}&page={{default-page}}' as const,
    pathParams: {} as { verifyStatus: string | number; defaultSize: string | number; defaultPage: string | number },
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as AppliedMentoringsResponse,
  },
  getMentorList: {
    method: 'GET' as const,
    path: '{{URL}}/mentors?region=미주권&size={{default-size}}&page={{default-page}}' as const,
    pathParams: {} as { defaultSize: string | number; defaultPage: string | number },
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as MentorListResponse,
  },
  getMentorDetail: {
    method: 'GET' as const,
    path: '{{URL}}/mentors/{{mentor-id}}' as const,
    pathParams: {} as { mentorId: string | number },
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as MentorDetailResponse,
  },
  getMyMentorPage: {
    method: 'GET' as const,
    path: '{{URL}}/mentor/my' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as MyMentorPageResponse,
  },
  putUpdateMyMentorPage: {
    method: 'PUT' as const,
    path: '{{URL}}/mentor/my' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, never>,
    body: {} as UpdateMyMentorPageRequest,
    response: {} as UpdateMyMentorPageResponse,
  },
  patchMentoringStatus: {
    method: 'PATCH' as const,
    path: '{{URL}}/mentor/mentorings/{{mentoring-id}}' as const,
    pathParams: {} as { mentoringId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as MentoringStatusRequest,
    response: {} as MentoringStatusResponse,
  },
  patchConfirmMentoring: {
    method: 'PATCH' as const,
    path: '{{URL}}/mentor/mentorings/check' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, never>,
    body: {} as ConfirmMentoringRequest,
    response: {} as ConfirmMentoringResponse,
  },
  getReceivedMentorings: {
    method: 'GET' as const,
    path: '{{URL}}/mentor/mentorings' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as ReceivedMentoringsResponse,
  },
  getUnconfirmedMentoringCount: {
    method: 'GET' as const,
    path: '{{URL}}/mentor/mentorings/check' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as UnconfirmedMentoringCountResponse,
  },
} as const;

export type MentorApiDefinitions = typeof mentorApiDefinitions;