import type { BoardListResponse, BoardResponse, CommentResponse, CreateCommentRequest, CreateCommentResponse, CreatePostResponse, LikePostResponse, PostDetailResponse, PostResponse, UpdateCommentRequest, UpdateCommentResponse, UpdatePostResponse } from './api';

export const communityApiDefinitions = {
  getBoardList: {
    method: 'GET' as const,
    path: '{{URL}}/boards' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as BoardListResponse,
  },
  getBoard: {
    method: 'GET' as const,
    path: '{{URL}}/boards/{{board-code}}' as const,
    pathParams: {} as { boardCode: string | number },
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as BoardResponse,
  },
  deleteComment: {
    method: 'DELETE' as const,
    path: '{{URL}}/comments/{{comment-id}}' as const,
    pathParams: {} as { commentId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as Record<string, never>,
    response: {} as CommentResponse,
  },
  patchUpdateComment: {
    method: 'PATCH' as const,
    path: '{{URL}}/comments/{{comment-id}}' as const,
    pathParams: {} as { commentId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as UpdateCommentRequest,
    response: {} as UpdateCommentResponse,
  },
  postCreateComment: {
    method: 'POST' as const,
    path: '{{URL}}/comments' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, never>,
    body: {} as CreateCommentRequest,
    response: {} as CreateCommentResponse,
  },
  deletePost: {
    method: 'DELETE' as const,
    path: '{{URL}}/posts/{{post-id}}' as const,
    pathParams: {} as { postId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as Record<string, never>,
    response: {} as PostResponse,
  },
  patchUpdatePost: {
    method: 'PATCH' as const,
    path: '{{URL}}/posts/{{post-id}}' as const,
    pathParams: {} as { postId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as Record<string, never>,
    response: {} as UpdatePostResponse,
  },
  postCreatePost: {
    method: 'POST' as const,
    path: '{{URL}}/posts' as const,
    pathParams: {} as Record<string, never>,
    queryParams: {} as Record<string, never>,
    body: {} as Record<string, never>,
    response: {} as CreatePostResponse,
  },
  getPostDetail: {
    method: 'GET' as const,
    path: '{{URL}}/posts/{{post-id}}' as const,
    pathParams: {} as { postId: string | number },
    queryParams: {} as Record<string, unknown>,
    body: {} as Record<string, never>,
    response: {} as PostDetailResponse,
  },
  postLikePost: {
    method: 'POST' as const,
    path: '{{URL}}/posts/{{post-id}}/like' as const,
    pathParams: {} as { postId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as Record<string, never>,
    response: {} as LikePostResponse,
  },
  deleteLikePost: {
    method: 'DELETE' as const,
    path: '{{URL}}/posts/{{post-id}}/like' as const,
    pathParams: {} as { postId: string | number },
    queryParams: {} as Record<string, never>,
    body: {} as Record<string, never>,
    response: {} as LikePostResponse,
  },
} as const;

export type CommunityApiDefinitions = typeof communityApiDefinitions;