export enum ReasonType {
  ADVERTISEMENT = "ADVERTISEMENT",
  SPAM = "SPAM",
  PERSONAL_INFO_EXPOSURE = "PERSONAL_INFO_EXPOSURE",
  PORNOGRAPHY = "PORNOGRAPHY",
  COPYRIGHT_INFRINGEMENT = "COPYRIGHT_INFRINGEMENT",
  ILLEGAL_ACTIVITY = "ILLEGAL_ACTIVITY",
  IMPERSONATION = "IMPERSONATION",
  INSULT = "INSULT",
}
