export { universitiesApi } from './api';
export { default as useDeleteWish } from './deleteWish';
export { default as useGetByRegionCountry } from './getByRegionCountry';
export { default as useGetIsWish } from './getIsWish';
export { default as useGetRecommendedUniversities } from './getRecommendedUniversities';
export { default as useGetUniversitySearchByFilter, type UniversitySearchFilterParams } from './getSearchFilter';
export { default as useUniversitySearch } from './getSearchText';
export { default as useGetUniversityDetail } from './getUniversityDetail';
export { default as useGetWishList } from './getWishList';
export { default as usePostAddWish } from './postAddWish';
