/**
 * React Query Keys
 * Bruno 폴더 구조를 기반으로 자동 생성됨
 */

export const QueryKeys = {
  Solid Connection: {
    folder: 'Solid Connection.folder' as const,
    postSignOut: 'Solid Connection.postSignOut' as const,
    postAppleAuth: 'Solid Connection.postAppleAuth' as const,
    postRefreshToken: 'Solid Connection.postRefreshToken' as const,
    postEmailLogin: 'Solid Connection.postEmailLogin' as const,
    postEmailVerification: 'Solid Connection.postEmailVerification' as const,
    postKakaoAuth: 'Solid Connection.postKakaoAuth' as const,
    deleteAccount: 'Solid Connection.deleteAccount' as const,
    postSignUp: 'Solid Connection.postSignUp' as const,
    getNewsList: 'Solid Connection.getNewsList' as const,
    deleteNews: 'Solid Connection.deleteNews' as const,
    putUpdateNews: 'Solid Connection.putUpdateNews' as const,
    postLikeNews: 'Solid Connection.postLikeNews' as const,
    deleteLikeNews: 'Solid Connection.deleteLikeNews' as const,
    postCreateNews: 'Solid Connection.postCreateNews' as const,
    postReport: 'Solid Connection.postReport' as const,
    getChatMessages: 'Solid Connection.getChatMessages' as const,
    getChatRooms: 'Solid Connection.getChatRooms' as const,
    patchReadChatRoom: 'Solid Connection.patchReadChatRoom' as const,
    getChatPartner: 'Solid Connection.getChatPartner' as const,
    getRecommendedUniversities: 'Solid Connection.getRecommendedUniversities' as const,
    getWishList: 'Solid Connection.getWishList' as const,
    위시 학교 삭제: 'Solid Connection.위시 학교 삭제' as const,
    postAddWish: 'Solid Connection.postAddWish' as const,
    위시 학교인지 조회: 'Solid Connection.위시 학교인지 조회' as const,
    학교 상세 정보 조회: 'Solid Connection.학교 상세 정보 조회' as const,
    getSearchText: 'Solid Connection.getSearchText' as const,
    getSearchFilter: 'Solid Connection.getSearchFilter' as const,
    getByRegionCountry: 'Solid Connection.getByRegionCountry' as const,
    patchInterestedRegionCountry: 'Solid Connection.patchInterestedRegionCountry' as const,
    patchProfile: 'Solid Connection.patchProfile' as const,
    getProfile: 'Solid Connection.getProfile' as const,
    patchPassword: 'Solid Connection.patchPassword' as const,
    getCompetitors: 'Solid Connection.getCompetitors' as const,
    postSubmitApplication: 'Solid Connection.postSubmitApplication' as const,
    getApplicants: 'Solid Connection.getApplicants' as const,
    getBoardList: 'Solid Connection.getBoardList' as const,
    getBoard: 'Solid Connection.getBoard' as const,
    deleteComment: 'Solid Connection.deleteComment' as const,
    patchUpdateComment: 'Solid Connection.patchUpdateComment' as const,
    postCreateComment: 'Solid Connection.postCreateComment' as const,
    deletePost: 'Solid Connection.deletePost' as const,
    patchUpdatePost: 'Solid Connection.patchUpdatePost' as const,
    postCreatePost: 'Solid Connection.postCreatePost' as const,
    getPostDetail: 'Solid Connection.getPostDetail' as const,
    postLikePost: 'Solid Connection.postLikePost' as const,
    deleteLikePost: 'Solid Connection.deleteLikePost' as const,
    postCreateLanguageTest: 'Solid Connection.postCreateLanguageTest' as const,
    getLanguageTestList: 'Solid Connection.getLanguageTestList' as const,
    postCreateGpa: 'Solid Connection.postCreateGpa' as const,
    getGpaList: 'Solid Connection.getGpaList' as const,
    putVerifyLanguageTest: 'Solid Connection.putVerifyLanguageTest' as const,
    putVerifyGpa: 'Solid Connection.putVerifyGpa' as const,
    getNicknameExists: 'Solid Connection.getNicknameExists' as const,
    postBlockUser: 'Solid Connection.postBlockUser' as const,
    deleteUnblockUser: 'Solid Connection.deleteUnblockUser' as const,
    getBlockedUsers: 'Solid Connection.getBlockedUsers' as const,
    getMatchedMentors: 'Solid Connection.getMatchedMentors' as const,
    postApplyMentoring: 'Solid Connection.postApplyMentoring' as const,
    patchConfirmMentoring: 'Solid Connection.patchConfirmMentoring' as const,
    getAppliedMentorings: 'Solid Connection.getAppliedMentorings' as const,
    getMentorList: 'Solid Connection.getMentorList' as const,
    getMentorDetail: 'Solid Connection.getMentorDetail' as const,
    getMyMentorPage: 'Solid Connection.getMyMentorPage' as const,
    putUpdateMyMentorPage: 'Solid Connection.putUpdateMyMentorPage' as const,
    patchMentoringStatus: 'Solid Connection.patchMentoringStatus' as const,
    getReceivedMentorings: 'Solid Connection.getReceivedMentorings' as const,
    getUnconfirmedMentoringCount: 'Solid Connection.getUnconfirmedMentoringCount' as const,
    getKakaoUserIds: 'Solid Connection.getKakaoUserIds' as const,
    deleteKakaoUnlink: 'Solid Connection.deleteKakaoUnlink' as const,
    getKakaoInfo: 'Solid Connection.getKakaoInfo' as const,
    collection: 'Solid Connection.collection' as const,
    dev: 'Solid Connection.dev' as const,
    local: 'Solid Connection.local' as const,
    postSlackNotification: 'Solid Connection.postSlackNotification' as const,
    postUploadLanguageTestReport: 'Solid Connection.postUploadLanguageTestReport' as const,
    postUploadProfileImage: 'Solid Connection.postUploadProfileImage' as const,
    postUploadProfileImageBeforeSignup: 'Solid Connection.postUploadProfileImageBeforeSignup' as const,
    postUploadGpaReport: 'Solid Connection.postUploadGpaReport' as const,
  },
} as const;

export type QueryKey = typeof QueryKeys[keyof typeof QueryKeys];