/**
 * React Query Keys
 * Bruno 폴더 구조를 기반으로 자동 생성됨
 */

export const QueryKeys = {
  Solid Connection: {
    folder: 'Solid Connection.folder' as const,
    로그아웃: 'Solid Connection.로그아웃' as const,
    애플 인증 (로그인 or 가입 코드 발급): 'Solid Connection.애플 인증 (로그인 or 가입 코드 발급)' as const,
    엑세스 토큰 재발급: 'Solid Connection.엑세스 토큰 재발급' as const,
    이메일 로그인: 'Solid Connection.이메일 로그인' as const,
    이메일 인증 (가입 코드 발급): 'Solid Connection.이메일 인증 (가입 코드 발급)' as const,
    카카오 인증 (로그인 or 가입 코드 발급): 'Solid Connection.카카오 인증 (로그인 or 가입 코드 발급)' as const,
    회원 탈퇴: 'Solid Connection.회원 탈퇴' as const,
    회원가입: 'Solid Connection.회원가입' as const,
    소식지 목록 조회: 'Solid Connection.소식지 목록 조회' as const,
    소식지 삭제: 'Solid Connection.소식지 삭제' as const,
    소식지 수정: 'Solid Connection.소식지 수정' as const,
    소식지 좋아요 삭제: 'Solid Connection.소식지 좋아요 삭제' as const,
    소식지 좋아요 추가: 'Solid Connection.소식지 좋아요 추가' as const,
    소식지 추가: 'Solid Connection.소식지 추가' as const,
    신고하기: 'Solid Connection.신고하기' as const,
    채팅 내역 조회: 'Solid Connection.채팅 내역 조회' as const,
    채팅방 목록 조회: 'Solid Connection.채팅방 목록 조회' as const,
    채팅방 읽음 처리: 'Solid Connection.채팅방 읽음 처리' as const,
    채팅방 파트너 조회: 'Solid Connection.채팅방 파트너 조회' as const,
    사용자 맞춤 대학 추천: 'Solid Connection.사용자 맞춤 대학 추천' as const,
    위시 학교 목록 조회: 'Solid Connection.위시 학교 목록 조회' as const,
    위시 학교 삭제: 'Solid Connection.위시 학교 삭제' as const,
    위시 학교 추가: 'Solid Connection.위시 학교 추가' as const,
    위시 학교인지 조회: 'Solid Connection.위시 학교인지 조회' as const,
    학교 상세 정보 조회: 'Solid Connection.학교 상세 정보 조회' as const,
    학교 텍스트 검색: 'Solid Connection.학교 텍스트 검색' as const,
    학교 필터 검색: 'Solid Connection.학교 필터 검색' as const,
    권역국가에 해당하는 전체 대학: 'Solid Connection.권역국가에 해당하는 전체 대학' as const,
    관심 권역국가 변경: 'Solid Connection.관심 권역국가 변경' as const,
    내 정보 수정: 'Solid Connection.내 정보 수정' as const,
    내 정보 조회: 'Solid Connection.내 정보 조회' as const,
    비밀번호 변경: 'Solid Connection.비밀번호 변경' as const,
    나의 지원과 동일한 지원자 현황 조회: 'Solid Connection.나의 지원과 동일한 지원자 현황 조회' as const,
    지원서 제출: 'Solid Connection.지원서 제출' as const,
    지원자 현황 조회: 'Solid Connection.지원자 현황 조회' as const,
    게시글 삭제: 'Solid Connection.게시글 삭제' as const,
    게시글 수정: 'Solid Connection.게시글 수정' as const,
    게시글 작성: 'Solid Connection.게시글 작성' as const,
    게시글 조회: 'Solid Connection.게시글 조회' as const,
    게시글 좋아요 등록: 'Solid Connection.게시글 좋아요 등록' as const,
    게시글 좋아요 삭제: 'Solid Connection.게시글 좋아요 삭제' as const,
    게시판 목록 조회: 'Solid Connection.게시판 목록 조회' as const,
    게시판 조회: 'Solid Connection.게시판 조회' as const,
    댓글 삭제: 'Solid Connection.댓글 삭제' as const,
    댓글 수정: 'Solid Connection.댓글 수정' as const,
    댓글 작성: 'Solid Connection.댓글 작성' as const,
    어학 성적 등록: 'Solid Connection.어학 성적 등록' as const,
    어학 성적 조회: 'Solid Connection.어학 성적 조회' as const,
    학점 등록: 'Solid Connection.학점 등록' as const,
    학점 조회: 'Solid Connection.학점 조회' as const,
    어학 검증 및 수정: 'Solid Connection.어학 검증 및 수정' as const,
    어학 조회: 'Solid Connection.어학 조회' as const,
    학점 검증 및 수정: 'Solid Connection.학점 검증 및 수정' as const,
    학점조회: 'Solid Connection.학점조회' as const,
    닉네임 중복 검증: 'Solid Connection.닉네임 중복 검증' as const,
    유저 차단 취소: 'Solid Connection.유저 차단 취소' as const,
    유저 차단: 'Solid Connection.유저 차단' as const,
    차단한 유저 목록 조회: 'Solid Connection.차단한 유저 목록 조회' as const,
    멘토 목록 조회: 'Solid Connection.멘토 목록 조회' as const,
    멘토 상세 페이지: 'Solid Connection.멘토 상세 페이지' as const,
    나의 멘토 페이지 수정: 'Solid Connection.나의 멘토 페이지 수정' as const,
    나의 멘토 페이지 조회: 'Solid Connection.나의 멘토 페이지 조회' as const,
    멘토링 수락거절: 'Solid Connection.멘토링 수락거절' as const,
    멘토링 확인: 'Solid Connection.멘토링 확인' as const,
    신청받은 멘토링 목록: 'Solid Connection.신청받은 멘토링 목록' as const,
    확인하지 않은 멘토링 수: 'Solid Connection.확인하지 않은 멘토링 수' as const,
    매칭된 멘토 목록: 'Solid Connection.매칭된 멘토 목록' as const,
    멘토링 신청: 'Solid Connection.멘토링 신청' as const,
    신청한 멘토링 목록: 'Solid Connection.신청한 멘토링 목록' as const,
    사용자 id 목록 조회: 'Solid Connection.사용자 id 목록 조회' as const,
    연결 끊기: 'Solid Connection.연결 끊기' as const,
    정보 조회: 'Solid Connection.정보 조회' as const,
    슬랙 알림: 'Solid Connection.슬랙 알림' as const,
    어학 성적표 업로드: 'Solid Connection.어학 성적표 업로드' as const,
    프로필 사진 업로드 (가입 전): 'Solid Connection.프로필 사진 업로드 (가입 전)' as const,
    프로필 사진 업로드 (가입 후): 'Solid Connection.프로필 사진 업로드 (가입 후)' as const,
    학적 성적표 업로드: 'Solid Connection.학적 성적표 업로드' as const,
    collection: 'Solid Connection.collection' as const,
    dev: 'Solid Connection.dev' as const,
    local: 'Solid Connection.local' as const,
  },
} as const;

export type QueryKey = typeof QueryKeys[keyof typeof QueryKeys];