export { universitiesApi } from './api';
export { universitiesApiDefinitions, UniversitiesApiDefinitions } from './apiDefinitions';
export * from './deleteWish';
export * from './getByRegionCountry';
export * from './getIsWish';
export * from './getRecommendedUniversities';
export * from './getSearchFilter';
export * from './getSearchText';
export * from './getUniversityDetail';
export * from './getWishList';
export * from './postAddWish';
