export { default as delete-게시글 삭제 } from './delete-게시글 삭제';
export { default as delete-게시글 좋아요 삭제 } from './delete-게시글 좋아요 삭제';
export { default as delete-댓글 삭제 } from './delete-댓글 삭제';
export { default as delete-소식지 삭제 } from './delete-소식지 삭제';
export { default as delete-소식지 좋아요 삭제 } from './delete-소식지 좋아요 삭제';
export { default as delete-위시 학교 삭제 } from './delete-위시 학교 삭제';
export { default as delete-유저 차단 취소 } from './delete-유저 차단 취소';
export { default as delete-회원 탈퇴 } from './delete-회원 탈퇴';
export { default as get-게시글 조회 } from './get-게시글 조회';
export { default as get-게시판 목록 조회 } from './get-게시판 목록 조회';
export { default as get-게시판 조회 } from './get-게시판 조회';
export { default as get-권역국가에 해당하는 전체 대학 } from './get-권역국가에 해당하는 전체 대학';
export { default as get-나의 멘토 페이지 조회 } from './get-나의 멘토 페이지 조회';
export { default as get-나의 지원과 동일한 지원자 현황 조회 } from './get-나의 지원과 동일한 지원자 현황 조회';
export { default as get-내 정보 조회 } from './get-내 정보 조회';
export { default as get-닉네임 중복 검증 } from './get-닉네임 중복 검증';
export { default as get-매칭된 멘토 목록 } from './get-매칭된 멘토 목록';
export { default as get-멘토 목록 조회 } from './get-멘토 목록 조회';
export { default as get-멘토 상세 페이지 } from './get-멘토 상세 페이지';
export { default as get-사용자 id 목록 조회 } from './get-사용자 id 목록 조회';
export { default as get-사용자 맞춤 대학 추천 } from './get-사용자 맞춤 대학 추천';
export { default as get-소식지 목록 조회 } from './get-소식지 목록 조회';
export { default as get-신청받은 멘토링 목록 } from './get-신청받은 멘토링 목록';
export { default as get-신청한 멘토링 목록 } from './get-신청한 멘토링 목록';
export { default as get-어학 성적 조회 } from './get-어학 성적 조회';
export { default as get-어학 조회 } from './get-어학 조회';
export { default as get-위시 학교 목록 조회 } from './get-위시 학교 목록 조회';
export { default as get-위시 학교인지 조회 } from './get-위시 학교인지 조회';
export { default as get-정보 조회 } from './get-정보 조회';
export { default as get-지원자 현황 조회 } from './get-지원자 현황 조회';
export { default as get-차단한 유저 목록 조회 } from './get-차단한 유저 목록 조회';
export { default as get-채팅 내역 조회 } from './get-채팅 내역 조회';
export { default as get-채팅방 목록 조회 } from './get-채팅방 목록 조회';
export { default as get-채팅방 파트너 조회 } from './get-채팅방 파트너 조회';
export { default as get-학교 상세 정보 조회 } from './get-학교 상세 정보 조회';
export { default as get-학교 텍스트 검색 } from './get-학교 텍스트 검색';
export { default as get-학교 필터 검색 } from './get-학교 필터 검색';
export { default as get-학점 조회 } from './get-학점 조회';
export { default as get-학점조회 } from './get-학점조회';
export { default as get-확인하지 않은 멘토링 수 } from './get-확인하지 않은 멘토링 수';
export { default as patch-게시글 수정 } from './patch-게시글 수정';
export { default as patch-관심 권역국가 변경 } from './patch-관심 권역국가 변경';
export { default as patch-내 정보 수정 } from './patch-내 정보 수정';
export { default as patch-댓글 수정 } from './patch-댓글 수정';
export { default as patch-멘토링 수락거절 } from './patch-멘토링 수락거절';
export { default as patch-멘토링 확인 } from './patch-멘토링 확인';
export { default as patch-비밀번호 변경 } from './patch-비밀번호 변경';
export { default as post-게시글 작성 } from './post-게시글 작성';
export { default as post-게시글 좋아요 등록 } from './post-게시글 좋아요 등록';
export { default as post-댓글 작성 } from './post-댓글 작성';
export { default as post-로그아웃 } from './post-로그아웃';
export { default as post-멘토링 신청 } from './post-멘토링 신청';
export { default as post-소식지 좋아요 추가 } from './post-소식지 좋아요 추가';
export { default as post-소식지 추가 } from './post-소식지 추가';
export { default as post-슬랙 알림 } from './post-슬랙 알림';
export { default as post-신고하기 } from './post-신고하기';
export { default as post-애플 인증 (로그인 or 가입 코드 발급) } from './post-애플 인증 (로그인 or 가입 코드 발급)';
export { default as post-어학 성적 등록 } from './post-어학 성적 등록';
export { default as post-어학 성적표 업로드 } from './post-어학 성적표 업로드';
export { default as post-엑세스 토큰 재발급 } from './post-엑세스 토큰 재발급';
export { default as post-연결 끊기 } from './post-연결 끊기';
export { default as post-위시 학교 추가 } from './post-위시 학교 추가';
export { default as post-유저 차단 } from './post-유저 차단';
export { default as post-이메일 로그인 } from './post-이메일 로그인';
export { default as post-이메일 인증 (가입 코드 발급) } from './post-이메일 인증 (가입 코드 발급)';
export { default as post-지원서 제출 } from './post-지원서 제출';
export { default as post-카카오 인증 (로그인 or 가입 코드 발급) } from './post-카카오 인증 (로그인 or 가입 코드 발급)';
export { default as post-프로필 사진 업로드 (가입 전) } from './post-프로필 사진 업로드 (가입 전)';
export { default as post-프로필 사진 업로드 (가입 후) } from './post-프로필 사진 업로드 (가입 후)';
export { default as post-학적 성적표 업로드 } from './post-학적 성적표 업로드';
export { default as post-학점 등록 } from './post-학점 등록';
export { default as post-회원가입 } from './post-회원가입';
export { default as put-나의 멘토 페이지 수정 } from './put-나의 멘토 페이지 수정';
export { default as put-소식지 수정 } from './put-소식지 수정';
export { default as put-어학 검증 및 수정 } from './put-어학 검증 및 수정';
export { default as put-채팅방 읽음 처리 } from './put-채팅방 읽음 처리';
export { default as put-학점 검증 및 수정 } from './put-학점 검증 및 수정';
